"""Message contracts between the services, for Python.

The source of truth is contracts/schemas/*.schema.json. The field
definitions live in `generated/` (pydantic models generated by
`just contracts`); the classes here extend them with what a schema can't
express in generated code: message IDs, blob-name resolution, and the
cross-field rule on the job's location. The TypeScript services generate
their types from the same schemas, and both languages' tests run the golden
messages in contracts/examples.

Evolution rules, so the services stay independently deployable:
  * Changes are additive only. Never rename or remove a field, and never
    change a field's meaning.
  * New fields get defaults. Readers ignore fields they don't know
    (`extra="ignore"`), so an older reader can process a newer message and
    the other way round.
"""

from __future__ import annotations

import uuid
from collections.abc import Mapping
from datetime import UTC, datetime
from enum import StrEnum
from urllib.parse import unquote, urlparse

from pydantic import AwareDatetime, ConfigDict, Field, model_validator

from docprocessor_shared.generated import document_uploaded_schema, extraction_completed_schema

# The type `ServiceBusMessage(application_properties=...)` declares. It mirrors
# the SDK's private `azure.servicebus._common.message.PrimitiveTypes`; `dict`
# is invariant, so a plain `dict[str, str]` does not type-check against it.
ApplicationProperties = dict[str | bytes, int | float | bytes | bool | str | uuid.UUID]

_CONFIG = ConfigDict(extra="ignore", frozen=True)


def application_properties(values: Mapping[str, str]) -> ApplicationProperties:
    """Copy string properties into the dict type Service Bus messages expect."""
    return {key: value for key, value in values.items()}


def blob_name_from_url(blob_url: str, container: str) -> str | None:
    """Return the decoded blob name from a blob URL in `container`, or None
    if the URL does not point into that container.

    Blob URLs are percent-encoded, while the SDK expects the raw name (it
    encodes it again when building request URLs), so the result is decoded.
    """
    path = urlparse(blob_url).path
    marker = f"/{container}/"
    idx = path.find(marker)
    if idx == -1:
        return None
    return unquote(path[idx + len(marker) :]) or None


def result_blob_name(tenant_id: str, doc_id: str) -> str:
    """Where the worker writes a document's extraction result, within the
    results container."""
    return f"{tenant_id}/{doc_id}.json"


# --------------------------------------------------------------------------
# document.uploaded: document service -> `document-events` topic; forwarded
# to the `extraction-jobs` queue, where the worker reads it as its job.
# --------------------------------------------------------------------------
class DocumentUploadedEvent(document_uploaded_schema.DocumentUploadedEvent):
    model_config = _CONFIG

    @model_validator(mode="after")
    def _has_location(self) -> DocumentUploadedEvent:
        # The schema's `not` rule, which code generation doesn't carry over.
        if not (self.blob_name or self.blob_url):
            raise ValueError("Neither blob_name nor blob_url is set.")
        return self

    @property
    def message_id(self) -> str:
        return self.doc_id

    def to_json(self) -> str:
        return self.model_dump_json()

    def resolve_blob_name(self, default_container: str) -> str:
        """The source blob's name: `blob_name`, or decoded from `blob_url`.

        Raises ValueError if neither yields a name.
        """
        if self.blob_name:
            return self.blob_name
        container = self.blob_container or default_container
        name = blob_name_from_url(self.blob_url or "", container)
        if name is None:
            raise ValueError(f"could not locate container '{container}' in blob URL '{self.blob_url}'")
        return name


# --------------------------------------------------------------------------
# Extraction completed: worker -> `extraction-results` topic.
# --------------------------------------------------------------------------
class ExtractionStatus(StrEnum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"


class ExtractionCompletedEvent(extraction_completed_schema.ExtractionCompletedEvent):
    model_config = _CONFIG

    # Narrowed from the generated Literal / Optional: an enum for callers, and
    # "now" when absent (the schema's documented reading).
    status: ExtractionStatus  # type: ignore[assignment]
    completed_at: AwareDatetime = Field(default_factory=lambda: datetime.now(UTC))  # type: ignore[assignment]

    @property
    def message_id(self) -> str:
        """Deterministic per (doc, status): with duplicate detection on the
        topic, a redelivered job does not produce a second event."""
        return f"{self.doc_id}:{self.status.value}"

    def to_json(self) -> str:
        return self.model_dump_json()

    def application_properties(self) -> ApplicationProperties:
        return application_properties({"tenant_id": self.tenant_id, "doc_id": self.doc_id, "status": self.status.value})

    def result_blob_name(self, results_container: str) -> str | None:
        """The result blob's name for a succeeded event (from the URL, falling
        back to the worker's path convention); None for a failed one."""
        if self.status is not ExtractionStatus.SUCCEEDED:
            return None
        from_url = blob_name_from_url(self.result_blob_url, results_container) if self.result_blob_url else None
        return from_url or result_blob_name(self.tenant_id, self.doc_id)
